version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jomishs
      POSTGRES_PASSWORD: "!20rekAmB[6:%"
      POSTGRES_DB: test
